version: "3.1"
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: nowaste
      MYSQL_USER: nowaste
      MYSQL_PASSWORD: passwordForGit
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  web:
    image: millarj/nowaste
    depends_on:
      - es
      - mysql
    links:
      - "mysql:mysql"
      - "es:es"
    environment:
      - DATABASE_URL=mysql+pymysql://nowaste:passwordForGit@mysql/nowaste
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 8000:5000